### ISSUE TITLE
Internal server error Java NullPointerException when using callAviAPI method

### ISSUE THREAD

**Issue by jbourrigaud** [avinetworks/avi-vrealize-orchestrator-plugin#172]
### Describe the bug

controller UI in v22.1.2
AVI plugin in v22.1.3
vra 8.11

i have created a workflow with Scriptable task to test callAviAPI method.

-- SC content --
//Declare AVI API Object
var myAviRunTimeInfo = new AviRunTimeInfo()
myAviRunTimeInfo.setHttpMethod("GET")
myAviRunTimeInfo.setUrl("cloud?vtype=CLOUD_NSXT")

//Start Try Catch on Run AVI API. THis will allow us to set a custom Error message on a failure.
try {
    //Run Avi API against the controller
    myAviRunTimeInfo = aviVroClient.callAviAPI(myAviRunTimeInfo)

System.debug("** REST API BODY response **")
System.debug(myAviRunTimeInfo.getResponseBody())

} catch (e) {
    throw "Please validate the provided Controller is up and run ther Workflow again. No roll backs need to be done at this point. The error received: "+e
}
----------------------------------------------------
Error logs display :

2023-07-06 14:56:33.303 +02:00ERRORError in (Workflow:AVI REST API - Get Clouds Details / Test REST API (item1)#16) Please validate the provided Controller is up and run ther Workflow again. No roll backs need to be done at this point. The error received: InternalError: java.lang.NullPointerException (Workflow:AVI REST API - Get Clouds Details / Test REST API (item1)#8)
2023-07-06 14:56:33.313 +02:00ERRORWorkflow execution stack:
***
item: 'AVI REST API - Get Clouds Details/item1', state: 'failed'// retrieve CLOUD, business state: 'null', exception: 'Please validate the provided Controller is up and run ther Workflow again. No roll backs need to be done at this point. The error received: InternalError: java.lang.NullPointerException (Workflow:AVI REST API - Get Clouds Details / Test REST API (item1)#8) (Workflow:AVI REST API - Get Clouds Details / Test REST API (item1)#16)'
workflow: 'AVI REST API - Get Clouds Details' (c3f0ef89-dcdf-4712-9985-729a1dd4a8ca) 
|  'attribute': name=tenant type=string value=admin
|  'attribute': name=controller type=string value=vqevominalbmgt01.naomipp.int
|  'attribute': name=aviVroClient type=Avi:AviVroClient value=dunes://service.dunes.ch/CustomSDKObject?id='vqevominalbmgt01.naomipp.int-admin'&dunesName='Avi:AviVroClient'
|  'output': name=cloudsAsJson type=string value=null
|  'no inputs'
*** End of execution stack.

### Reproduction steps

1. copy and paste the SC content in any workflow
2. implement variables as presented in the description
3. execute the vro workflow

i dont understand the issue. i presume it is plugin internal error

### Expected behavior

the REST API is executed with success

**Comment by jbourrigaud** [comment]
To give you more details, i was able to collect log bundle with error :
see extract 

2023-07-10T15:01:09.257Z INFO vco [host='vco-app-5d896c9d8f-7jt8l' thread='WorkflowExecutorPool-Thread-1' user='joel.Bourrigaud' org='39f7bfb0-a351-4aab-947c-e441445c63c6' trace='-'] {|__SYSTEM|joel.Bourrigaud:AVI REST API - Get Clouds Details:c3f0ef89-dcdf-4712-9985-729a1dd4a8ca:token=c88b7ad3-2475-4f1d-910f-b1d63a2dccf4} ch.dunes.scripting.server.script.MainScriptingObject - executeScript //Declare AVI API Object
var myAviRunTimeInfo = new AviRunTimeInfo()
myAviRunTimeInfo.setHttpMethod("GET")
myAviRunTimeInfo.setUrl("cloud?vtype=CLOUD_NSXT")

//Start Try Catch on Run AVI API. THis will allow us to set a custom Error message on a failure.
try {
System.debug("aviVroClient="+aviVroClient)
System.debug("myAviRunTimeInfo="+myAviRunTimeInfo)

    //Run Avi API against the controller
    myAviRunTimeInfo = aviVroClient.callAviAPI(myAviRunTimeInfo)
//    cloudsAsJson = JSON.parse(myAviRunTimeInfo.getResponseBody())

System.debug("** REST API BODY response **")
System.debug(myAviRunTimeInfo.getResponseBody())

} catch (e) {
    throw "The error received: "+e
} Workflow:AVI REST API - Get Clouds Details / Test REST API (item1)
2023-07-10T15:01:09.258Z INFO vco [host='vco-app-5d896c9d8f-7jt8l' thread='WorkflowExecutorPool-Thread-1' user='joel.Bourrigaud' org='39f7bfb0-a351-4aab-947c-e441445c63c6' trace='-'] {|__SYSTEM|joel.Bourrigaud:AVI REST API - Get Clouds Details:c3f0ef89-dcdf-4712-9985-729a1dd4a8ca:token=c88b7ad3-2475-4f1d-910f-b1d63a2dccf4} ch.dunes.scripting.server.script.MainScriptingObject - executeScript exec org.mozilla.javascript.InterpretedFunction@3ccb876d
2023-07-10T15:01:09.262Z DEBUG vco [host='vco-app-5d896c9d8f-7jt8l' thread='WorkflowExecutorPool-Thread-1' user='joel.Bourrigaud' org='39f7bfb0-a351-4aab-947c-e441445c63c6' trace='-'] {|__SYSTEM|joel.Bourrigaud:AVI REST API - Get Clouds Details:c3f0ef89-dcdf-4712-9985-729a1dd4a8ca:token=c88b7ad3-2475-4f1d-910f-b1d63a2dccf4} SCRIPTING_LOG - [AVI REST API - Get Clouds Details (7/10/23 15:01:07)] aviVroClient=DynamicWrapper (Instance) : [AviVroClient]-[class com.vmware.avi.vro.AviVroClient] -- VALUE : com.vmware.avi.vro.AviVroClient@12972445
2023-07-10T15:01:09.264Z DEBUG vco [host='vco-app-5d896c9d8f-7jt8l' thread='WorkflowExecutorPool-Thread-1' user='joel.Bourrigaud' org='39f7bfb0-a351-4aab-947c-e441445c63c6' trace='-'] {|__SYSTEM|joel.Bourrigaud:AVI REST API - Get Clouds Details:c3f0ef89-dcdf-4712-9985-729a1dd4a8ca:token=c88b7ad3-2475-4f1d-910f-b1d63a2dccf4} SCRIPTING_LOG - [AVI REST API - Get Clouds Details (7/10/23 15:01:07)] myAviRunTimeInfo=DynamicWrapper (Instance) : [AviRunTimeInfo]-[class com.vmware.avi.vro.AviRunTimeInfo] -- VALUE : com.vmware.avi.vro.AviRunTimeInfo@2a9388ee
2023-07-10T15:01:09.264Z WARN vco [host='vco-app-5d896c9d8f-7jt8l' thread='WorkflowExecutorPool-Thread-1' user='joel.Bourrigaud' org='39f7bfb0-a351-4aab-947c-e441445c63c6' trace='-'] {|__SYSTEM|joel.Bourrigaud:AVI REST API - Get Clouds Details:c3f0ef89-dcdf-4712-9985-729a1dd4a8ca:token=c88b7ad3-2475-4f1d-910f-b1d63a2dccf4} ch.dunes.vso.sdk.WrappedJavaMethod - Invocation exception during 'public com.vmware.avi.vro.AviRunTimeInfo com.vmware.avi.vro.AviVroClient.callAviAPI(com.vmware.avi.vro.AviRunTimeInfo) throws java.lang.Exception' call on object 'com.vmware.avi.vro.AviVroClient@12972445'
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at ch.dunes.vso.sdk.WrappedJavaMethod.invoke(WrappedJavaMethod.java:233) ~[o11n-sdkcenter-8.11.1.jar:?]
	at ch.dunes.vso.sdk.WrappedJavaMethod.call(WrappedJavaMethod.java:175) [o11n-sdkcenter-8.11.1.jar:?]
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1473) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:120) [rhino-1.7R4.jar:1.7R4]
	at ch.dunes.scripting.server.script.MainScriptingObject.executeScript(MainScriptingObject.java:278) [o11n-scriptingengine-8.11.1.jar:?]
	at ch.dunes.scripting.server.script.MainScriptingObject.executeScript(MainScriptingObject.java:262) [o11n-scriptingengine-8.11.1.jar:?]
	at ch.dunes.workflow.engine.mbean.WorkflowScriptRunner.execute(WorkflowScriptRunner.java:209) [o11n-scriptingengine-8.11.1.jar:?]
	at ch.dunes.workflow.engine.mbean.runner.WorkflowItemTaskRunner.execute(WorkflowItemTaskRunner.java:45) [o11n-scriptingengine-8.11.1.jar:?]
	at ch.dunes.workflow.engine.mbean.runner.WorkflowItemTaskRunner.execute(WorkflowItemTaskRunner.java:26) [o11n-scriptingengine-8.11.1.jar:?]
	at ch.dunes.workflow.engine.mbean.helper.WorkflowHandler.executeItem(WorkflowHandler.java:1380) [o11n-scriptingengine-8.11.1.jar:?]
	at ch.dunes.workflow.engine.mbean.helper.WorkflowHandler.requestElementExecution(WorkflowHandler.java:1330) [o11n-scriptingengine-8.11.1.jar:?]
	at ch.dunes.workflow.engine.mbean.helper.WorkflowHandler.handleWorkflowTokenNextStep(WorkflowHandler.java:976) [o11n-scriptingengine-8.11.1.jar:?]
	at ch.dunes.workflow.engine.mbean.helper.WorkflowHandler.executeToken(WorkflowHandler.java:855) [o11n-scriptingengine-8.11.1.jar:?]
	at ch.dunes.workflow.engine.mbean.helper.WorkflowHandler.handleTokenExecution(WorkflowHandler.java:781) [o11n-scriptingengine-8.11.1.jar:?]
	at ch.dunes.workflow.engine.mbean.helper.WorkflowHandler$1.execute(WorkflowHandler.java:475) [o11n-scriptingengine-8.11.1.jar:?]
	at ch.dunes.workflow.engine.mbean.helper.WorkflowHandler$1.execute(WorkflowHandler.java:472) [o11n-scriptingengine-8.11.1.jar:?]
	at ch.dunes.model.ar.AccessRightsTemplate.executeWithAccessRights(AccessRightsTemplate.java:15) [o11n-model-8.11.1.jar:?]
	at ch.dunes.workflow.engine.mbean.helper.WorkflowHandler.doExecute(WorkflowHandler.java:472) [o11n-scriptingengine-8.11.1.jar:?]
	at ch.dunes.workflow.engine.mbean.helper.WorkflowHandler.run(WorkflowHandler.java:287) [o11n-scriptingengine-8.11.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
	at com.vmware.avi.vro.AviVroClient.getSslService(AviVroClient.java:102) ~[o11nplugin-vro-core-22.1.3.3.RELEASE.jar:?]
	at com.vmware.avi.vro.AviVroClient.getRestTemplate(AviVroClient.java:109) ~[o11nplugin-vro-core-22.1.3.3.RELEASE.jar:?]
	at com.vmware.avi.vro.AviVroClient.callAviAPI(AviVroClient.java:470) ~[o11nplugin-vro-core-22.1.3.3.RELEASE.jar:?]
	... 32 more
